### ISSUE TITLE
images and leaflet folder not copied on installation

### ISSUE THREAD

**Issue by tcuje** [Schlumpf/osmodul#1]
I just downloaded http://jextensions.hof-ronig.de/mod_osmod/mod_osmod_v27.zip and installed it via package installation, but unfortunately the "images" folder and the "leaflet" folder are not copied to the modules folder.

On first sight this results in a missing tutorial picture in the description.

I guess there is something wrong with the installation script, because the folders exist in the downloaded zip file.

I'm using Joomla 3.4.x

**Comment by Schlumpf** [comment]
The folders are copied to the "media" folder. That's correct. I changed it in v2.7 according to the Jooma guidelines.
The missing image was a wrong link in the translation files. It was still pointing to the not existing image module directory.
