### ISSUE TITLE
MapQuest not working anymore

### ISSUE THREAD

**Issue by ghanastic** [Schlumpf/osmodul#12]
Just for your information: It seems that access to OpenStreetMap using the MapQuest style has changed. Instead of the map the following message ist displayed: "As of July 11, 2016, direct tile access has been discontinued." When using another style (for example: OpenStreetMap DE) in OSModul the map will be displayed as expected.

**Comment by Schlumpf** [comment]
Thanks for information.
Sadly, at the moment I can't do anything to get it working again. So I removed the support for MapQuest.
Proposals for alternatives are welcome.
