### ISSUE TITLE
coördinates inversed and marker (pin) not in the center

### ISSUE THREAD

**Issue by fcocquit** [Schlumpf/osmodul#13]
I just installed osmod, which is quite simple to use, but i coud not get the pin locate to the right point. When i changed however the longitude and the latitude it did. And a second issue: when opening the webpage with the module, the pin is not in the center but just outside the right border. How can i change this?
![image](https://cloud.githubusercontent.com/assets/11227394/17017620/50e785fe-4f34-11e6-9857-ef85bba2d23d.png)

**Comment by Schlumpf** [comment]
Hi @fcocquit,
could you send me a link to you website? Then I can take a look. You can mail me, if you don't want to make the link public. I assume it has something to do with your template. What are the coordinates, you want to show?

best regards

**Comment by fcocquit** [comment]
Hello,

I assume you want to visit the backend. So i created a user account with
super user rights
Username: Schlumpf
Pasword: 20160721
Website: sitedemo.freddycocquit.be/administrator (website being under
construction).
You'll find the coordinates in de module.

Kind regards

Freddy
Op donderdag 21 juli 2016 heeft Schlumpf <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> het volgende
geschreven:

**Comment by fcocquit** [comment]
Hi,

Site is still under construction.
How can i mail you directly?

**Comment by fcocquit** [comment]
Wrong button....:-)

**Comment by Schlumpf** [comment]
You can find my mail address at the top of almost every file of the module ;)

**Comment by fcocquit** [comment]
Did you receive my mail?

Kind regards

**Comment by Schlumpf** [comment]
yes ;)

**Comment by fcocquit** [comment]
Hello,
already any clue?

**Comment by fcocquit** [comment]
hello,

i sent you yesterday a mail, but i am not sure it came through: did you find a solution?

kind regards

**Comment by Schlumpf** [comment]
The problem is the way, your template implemented the responsive layout. It seems, that the module positions and sizes are changed by the template after loading the page and the map doesn't notice it.

I discovered a workaround for that:
Add `<script type="text/javascript">map125._onResize();</script>` to the "HTML after" field in the module settings (first page). This will force the map to resize.

Does it work for you?
best regards

**Comment by fcocquit** [comment]
I am not able to test this at the moment. I will try this tomorrow evening.
Thank you!

Op woensdag 10 augustus 2016 heeft Schlumpf <notifications@github.com> het
volgende geschreven:

**Comment by fcocquit** [comment]
hmm: i added this, enabled the module but nothing is showing up in the frontend (when i enable "show title" the title is visible). I must be doing something wrong... Maybe i should give you accessrights so you can have a look in the back end?

**Comment by fcocquit** [comment]
update: i could make the module visible, but adding the script didn't work.

**Comment by Schlumpf** [comment]
See my mails ;)

**Comment by fcocquit** [comment]
i just sent you a private mail :-)

**Comment by Schlumpf** [comment]
Done :)

The number ’125’ in my post from yesterday is the module ID. On a new site, it can be different. You habe to replace it by the module ID oft your site.

**Comment by fcocquit** [comment]
worked fine! But now the module itself is "dislocated": it has moved down.
Should i ad some negative padding?

2016-08-11 8:35 GMT+02:00 Schlumpf <notifications@github.com>:

**Comment by Schlumpf** [comment]
This has nothing to do with OSModul, you had a module "BT Google Maps" enabled. I deactivated it. ;)

**Comment by fcocquit** [comment]
That was really stupid of me.....  i really feel embarrased.
I had just figured that out for myself, but you were faster. :-)
Thank you very much, I will give you a very good score on the extensions
website!

Kind regards!

2016-08-11 9:02 GMT+02:00 Schlumpf <notifications@github.com>:

**Comment by Schlumpf** [comment]
Many thanks :)
