### ISSUE TITLE
Karte wird nicht geladen

### ISSUE THREAD

**Issue by yoda333** [Schlumpf/osmodul#15]
Im Firefox werden keine gpx Dateien mehr geladen, nachdem ich die Seite auf SSL umgestellt habe. 
In der Konsole von Firefox bekomme ich folgende Fehler:

Laden von gemischten aktiven Inhalten "http://www.openlayers.org/api/OpenLayers.js" wurde blockiert.[Weitere Informationen] gesamtroute
Laden von gemischten aktiven Inhalten "http://www.openstreetmap.org/openlayers/OpenStreetMap.js" wurde blockiert.[Weitere Informationen]

Sind die URLs im Modul hinterlegt? Wenn ja, wäre eine Umstellung auf https möglich?

Gruß
Patrick

**Comment by Schlumpf** [comment]
Hi @yoda333,
bist du sicher, dass das mit OSModul zu tun hat? Ich benutze Leaflet.js zur Kartendarstellung und nicht OpenLayers. Ich habe auch auf den ersten Blick nichts von OpenLayers in den Sourcen von Leaflet gefunden.

Viele Grüße
Martin

**Comment by yoda333** [comment]
Hallo Martin,

du hast recht. Es hat nichts mit OSModul zu tun. Sorry.
Es lag an GPXTrackMap, was ich am Ende der Testphase genommen hatte.
Das OSModul war noch installiert. 

Gruß
Patrick
