### ISSUE TITLE
Leaflet is not loaded when I {loadposition} the module

### ISSUE THREAD

**Issue by oswajas** [Schlumpf/osmodul#16]
When I {loadposition} the module into an article, Leaflet is not loaded, leading to a reference error "L is not defined".

**Comment by Schlumpf** [comment]
Hi @oswajas ,
I tested that and it works fine for me. I need more information to find your problem.

Best regards
Martin

**Comment by oswajas** [comment]
I template's index.php says `JFactory::getDocument()->_scripts = array()` right at the top. what confused me (and still does) was, that still Leaflet is loaded when the module is displayed at one of the standard positions  of the template.
