### ISSUE TITLE
OSModul - no map ist shown

### ISSUE THREAD

**Issue by Elchsammler** [Schlumpf/osmodul#26]
Hello,

i tried to use OSModul with Joomla 3.8 and jsn solid template.

![image](https://user-images.githubusercontent.com/32275604/30823444-744a9d0a-a22c-11e7-932e-a8f63f02b4ff.png)

Can anybody help me?

Greets
Thomas

**Comment by rpbikker** [comment]
Hi, 

I have the same error, also using Joomla 3.8.0, but I don't know if that's related.

I worked around it by copying the media/mod_osmod/leaflet/images/marker-icon.png to some place under images/ and using that copy as custom icon. Same can be done for the shadow, if you want that.

**Comment by Elchsammler** [comment]
Hi, thank You for the answer. Unfortunally it doesn't work although.

**Comment by rpbikker** [comment]
I'm sorry to hear that, but I can't help you. It works at my test server, for unknown reasons. However, I can't reproduce this on my production server, which is still at Joomla 3.7.5. 

I've walked away from this module. I don't think it will be maintained. Trying GPXTrackMap now...

**Comment by Schlumpf** [comment]
Hi @Elchsammler,
I can't reproduce your problem. I have 2 Joomla 3.8 installations on different servers online and working.
Maybe you could provide a public link to your site? Than I could take a look.
There are known problems with optimisation addons, do you use such plugins.

Best regards
Schlumpf

**Comment by Elchsammler** [comment]
Thank you Martin for your answer and sorry for the late reaction from me. 

You can see the problem here:. http://test04.s4.ak-internet.de/

Best regards 
Elchsammler

**Comment by jojo12** [comment]
I am using the osmodul on a clean Joomla! 3.8.1 with the official joomla template protostar (with ja_purity_iii too). I encountered no such problems. Please try, if it works on the official protostar and additional plugins disabled. If it works with that, then there must be an interference between your template or an additional plugin.

**Comment by Schlumpf** [comment]
@Elchsammler your template supports a "[CSS/JS Compression](http://demo.joomlashine.com/joomla-templates/jsn_solid_2/pro/index.php/advanced-stuff/2016-06-20-07-19-21/css-js-compression)". Maybe you could turn it off for testing. There are some known problems with some optimisation plugins like [JCH Optimize](https://github.com/Schlumpf/osmodul/wiki/JCH-Optimize-and-others).

**Comment by Elchsammler** [comment]
Thank you. I could see that the template is the problem.
