### ISSUE TITLE
PHP 7.2 Warning : count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by rizraz** [Schlumpf/osmodul#32]
Hi,
this warning I get after update php to version 7.2:
"Warning : count(): Parameter must be an array or an object that implements Countable in ~/modules/mod_osmod/heler.php on line 35"

Since php 7.2 an argument of count may be not NULL or empty.

My workaround is: if (!empty($params->get('scale'))) { .... }

**Comment by Schlumpf** [comment]
Hi,
yes you are right. Maybe you could test the fix? https://github.com/Schlumpf/osmodul/archive/php72-fix.zip I'll publish a new version if it works fine.

**Comment by rizraz** [comment]
Hi Schlumpf,
thank you, for me it works. No error messages anymore.

**Comment by Schlumpf** [comment]
Fixed in v2.16.

Please note that OSModul has moved to Gitlab: https://gitlab.com/schlumpf/osmodul
