### ISSUE TITLE
Additional text on top of map

### ISSUE THREAD

**Issue by MGampper** [Schlumpf/osmodul#33]
I can't find any explanation how to add addition description text on top or below of map. Can you please give hints if this is possilble

**Comment by Schlumpf** [comment]
Unfortunately, there is no provision for such a possibility.
Since it is a module, you could add a custom-HTML-module at the same position with hidden title to archive something like this.

**Comment by MGampper** [comment]
Thanks for your fast feedback. Explained the idea behind. I close the issue. Great solution.
