### ISSUE TITLE
No map showing, only grey frame

### ISSUE THREAD

**Issue by ArjanMyer** [Schlumpf/osmodul#4]
Hello Martin,

we installed your module, but can't get it to view a map... We entered the coordinates and the frame with the zoom-tool is visible, but no map is being displayed, only a grey frame.

You can take a look at http://www.sportclubrijssen.nl/nl/informatie/locatie

For your information: we are using Joomla 3.4.8 with the (latest) Gantry 5 (version 5.2.6) Framework and the (latest) Gantry 5 based template "Hydrogen".

Thanks in advance for looking into it...

Regards,

Arjan.

**Comment by Schlumpf** [comment]
Hi Arjan,
I've seen, that you are using "jchoptimize". Could you deactive that plugin for testing?

Best regards,
Martin

**Comment by ArjanMyer** [comment]
Goodmorning Martin,

thank you very much for your fast reply. I disabled JCH Optimize and that was actually the solution to the problem. Should I exclude the JavaScript-code that accompanies your (by the way fantastic) extension in JCH Optimize?

Regards,

Arjan.

**Comment by Schlumpf** [comment]
I've no experience with JCH Optimize. If it is possible, yes please do it and I'll write some notes to the docs. Please tell me, if I can close this issue.

PS: I would be happy about writing a review on JED.

**Comment by ArjanMyer** [comment]
The problem lies with the JavaScript-file 'leaflet.js'. I have excluded it within JCM Optimize and now OSModul is functioning properly with JCM Optimize enabled. So generally, 'leaflet.js' should be excluded from Caching Optimizers within Joomla. 

For your documentation-convenience I have written down the instructions to exclude the file from being processed by JCH Optimize:

Go to the Joomla-menu 'Extensions', select 'Plugins' from this menu, search for "JCH Optimize", click this plugin, select the tab 'Exclude Options', scroll to the part 'Exclude files and extensions from aggregation' and in the field 'Exclude JavaScript Files' enter "leaflet.js" (without the quotes), then click the button 'Add item' and click the button 'Save' on top of the screen to save the plugin settings.

Other Cache Optimizers have a similar way of excluding files from processing.

And of course you will get a (positiv) review on JED :-)

Regards,

Arjan.

**Comment by jwiesel** [comment]
@ArjanMyer: Thanks for the explanation. My workaround till now was to change the JCH-Optimize level from Average to Intermediate. But I just switched to your solution as it results in a higher GTmetrix score

**Comment by Schlumpf** [comment]
I added @ArjanMyer's explanation to the wiki. Many thanks for investigating the problem :+1:
Please reopen this issue, if there are more problems.

**Comment by becmar39** [comment]
Hi Martin,
on my Site http://sv-kleinsendelbach.de/anfahrt I have the same problem using Osmodul. It works fine for a couple of days. I do not use JCH-Optimize.

Any suggestions?

Thanks in advance.

**Comment by Schlumpf** [comment]
Hi @becmar39,
you are using something optimizing or zipping, too. Your pages are delivered as `gzip.php`. Does your template has such a functionality? What template are you using?

best regards
Martin

**Comment by becmar39** [comment]
Hi @Schlumpf,
thanks for your help. This exactly was the problem. Iam Using blue2 Template based on Warp Theme Framework 7.3.7

When turning off "Minify+Data Uris+Gzip" the map is shown.
Compression only with "Minify+ Data Uris" shows the map, but Pin is not shown.
Turning off completly brings OS Modul to work.

Best regards,

**Comment by ArjanMyer** [comment]
Hi @becmar39 ,

maybe an idea to switch off the integrated compression in the template settings and use a third party optimizer where you can do more detailed settings (JCH Optimize for example).

Regards,

Arjan.

**Comment by ArjanMyer** [comment]
Hi @Schlumpf,

a little bit late, but thanks for the credits. Appreciate it!

Regards,

Arjan.
