### ISSUE TITLE
how to avoid "Strict Standards:  Only variables should be assigned by reference in..." error

### ISSUE THREAD

**Issue by francescomarucci** [Schlumpf/osmodul#5]
hello,
in order to avoid this PHP error:
"Strict Standards:  Only variables should be assigned by reference in..."

I had to modify the line 15 of the "mod_osmod.php" file from:
$document =& JFactory::getDocument();
to:
$document = JFactory::getDocument();

I just downloaded the last version of Joomla (3.4.7) and of the OSModul and I'm in the Italian Aruba host where my configuration is:
http://www.capovaccaio.it/ver.php

after the correction all is working well:
http://www.capovaccaio.it/cms/index.php/contatti

thanks a lot!
good job,
francesco

**Comment by Schlumpf** [comment]
I fixed that issue in v2.9. Are you sure, that you are using the latest version?

**Comment by francescomarucci** [comment]
you have right: I installed the 2.8 version, but this is the version installed (today) by default from the Joomla WEB installer (as the attached screenshot shows).

![install_default_ver2 8](https://cloud.githubusercontent.com/assets/1571351/12022144/49af850a-ad8d-11e5-98db-1a115d518344.PNG)

may be they have to update the link in the repository, at the moment it is:
http://jextensions.hof-ronig.de/mod_osmod/mod_osmod_v28.zip

thanks.

regards,
francesco

**Comment by Schlumpf** [comment]
oops, you are right. I forgot to update the link. Now it should be correct. Please test again.

**Comment by francescomarucci** [comment]
I still can not see the updated link, but maybe I'm viewing the cache... I tried to clear cache and to set 0 hours to the preferences update cache, but the 2.8 is still there.
I updated manually, it is not important.

thanks a lot,
francesco

**Comment by Schlumpf** [comment]
OK, I close this issue as fixed in v2.9.
Please reopen, if you have still problems.
