### ISSUE TITLE
Only grey frame showing when popup is defined

### ISSUE THREAD

**Issue by ArjanMyer** [Schlumpf/osmodul#6]
Martin,

when I define an extra markerpin with the following line it is working properly:

`#parking{(52.295082,6.520745),,};`

but when I use the following line (to get a text popup with the markerpin) I get a grey frame:

`#parking{(52.295082,6.520745),,{#parkpop,immediately}};`

I  have defined the popup using the following line:

`#parkpop{Parkeren};`

I made shure that no Caching Optimizer is active within the Joomla-installation.

Any idea what could be the problem? Based on you documentation, I can't see any typos.

Regards,

Arjan.

**Comment by Schlumpf** [comment]
OK, that is a bug.
I found it in helper.php line 134.
replace `always` with `immediately`.

I'll fix it in the next version, thanks for reporting.

Best regards,
Martin

**Comment by ArjanMyer** [comment]
You're welcome...

To tidy-up the code I presume that line 144:

`if($treffer['show'] == 'always' | $treffer['show'] == 'immediately') $ret .= '.openPopup()';`

should then also be changed to:

`if($treffer['show'] == 'immediately') $ret .= '.openPopup()';` ?

Regards,

Arjan.
