### ISSUE TITLE
Calling marker to pop-up

### ISSUE THREAD

**Issue by February2** [Schlumpf/osmodul#7]
Hi Guys,
can someone tell me how to call particular marker on map to pop-up when button in joomla article was clicked? Suggested tip (<span onclick="map87.panTo(marker87.getLatLng()); map87.setZoom(17);">Sydney</span>)  in osm modul wiki doesn't work for me. I have changed the map & marker IDs and clicking on word "SYDNEY" does nothing...

Thank You in advance for help :-)

**Comment by Schlumpf** [comment]
Hi,
there is a snare. Joomla's TinyMCE editor strips down the HTML code an removes the `span` element. I updated the wikipage and found a workaround.

Please tell me if it works for you or if you have still problems.

**Comment by February2** [comment]
Nah, it doesn't work :-(
Maybe I do something wrong?

website's address (work in progress): http://wleborku.pl/index.php?option=com_content&view=article&id=6:i-urzad-pocztowy-lebork&catid=18&Itemid=122

**Comment by Schlumpf** [comment]
You have to write `mpM110_up1`. With `M`, not `P`.
By the way, on the latest wiki update, I changed the `onclick=...` code, but your problem is the `P`.

**Comment by February2** [comment]
Yep! You are right :-) Thank You

If You find a spare moment - function provided in tips&tricks focuses map on marker but without Pop-up ;-)
