### ISSUE TITLE
Path to files (js, css, ...) not (always) correct

### ISSUE THREAD

**Issue by googol42** [Schlumpf/osmodul#8]
Hello,

Setup:
- mod_rewirte on
- OSMmodul embedded on page: example.org/my-site/about/where (note: my site's root is example.org/my-site/)

Result:
The paths to the js, css, and other files are wrong. Instead of *example.org/my-site/media/mod_osmod/leaflet/leaflet.css* the URL *example.org/my-site/***about***/media/mod_osmod/leaflet/leaflet.css* is requested by the browser.

Regards

**Comment by Schlumpf** [comment]
Thanks for reporting.
Please try this fix: https://github.com/Schlumpf/osmodul/archive/root-dir.zip
Does it resolve the problem?

**Comment by googol42** [comment]
Sorry, I have been working quite a lot on my site and cannot test this (I use now non hierarchic  paths)

**Comment by nounours77** [comment]
Dear Martin,
I had the exact same problem. (even after upgrading to 2.11 from may!)
Your test version does solve the problem for me! Perfect!

thanks, nounours

**Comment by Schlumpf** [comment]
Hi @nounours77,
thanks for the reply. Now I merged the fixed version to the master branch and it will available for all.

best regards
Martin
