### ISSUE TITLE
Establish OSM connection via https instead of http

### ISSUE THREAD

**Issue by jwiesel** [Schlumpf/osmodul#9]
Dear Schlumpf,
first of all thank you for the neat joomla module. It is really helpful and works perfectly for my case.
I just realized, that the Firefox console complains about loading http content in my https secured website.
I just made a quick check to simply replace the http:// entries to openstreetmap by https:// in helper.php. Then the console messages are gone. As openstreetmap uses ssl by default, it should also work for other sites.
Can you update the module accordingly for the next version? :-)
Thanks!

**Comment by Schlumpf** [comment]
Fixed in #10.
I switched to https on supporting servers.
